server:
  port: 8090
  servlet:
    context-path: /search
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lytdata?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: liyitong
    password: liyitong
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    neo4j:
      uri: bolt://192.168.30.130:7687
      username: neo4j
      password: letmein