server:
  port: 8090

spring:
  data:
    neo4j:
      uri: bolt://192.168.30.131:7687
      username: neo4j
      password: 123456
  elasticsearch:
    rest:
      uris: ["http://192.168.30.131:9200", "http://192.168.30.132:9200"]